### ISSUE TITLE
Bug on Windows, NodeJS POSIX vs. Windows paths

### ISSUE THREAD

**Issue by akaleeroy** [marisademeglio/eleventypub#5]
Tried it on Windows and building fails because of a paths issue. On Windows all the item paths in the resources folder are written as

```js
[
  "D:\\path\\to\\my\\project\\resources\\css\\page.css",
  // etc.
]
```

I think [utils.js > walk #L10](https://github.com/marisademeglio/eleventypub/blob/10a445989ddcfb4fa63b0c60f239cc63f3d3c5bf/utils.js#L10) needs to be

```js
            let itemPath = path.posix.join(dir, item);
```

This seems to make `walk()` produce the correct `resources.json` file:

```js
[
  "resources/css/page.css",
  // etc.
]]
```

Luckily this problem is [literally the first section in the NodeJS `path` documentation](https://devdocs.io/node/path#windows-vs-posix) so I was able to figure it out. :smile: 

Thank you!

**Comment by marisademeglio** [comment]
Oh thanks for looking into it, I don't use windows so this tool that I initially just wrote for myself is probably inadvertently biased. The next time I make any updates I'll have a look including at the fix you mention.
