### ISSUE TITLE
Multi level TOC

### ISSUE THREAD

**Issue by gautierchomel** [marisademeglio/eleventypub#6]
Hello, and thanks for this great generator.  I am using it to build [Thorium Reader documentation as EPUB](https://github.com/edrlab/thorium-reader-doc). 

I want to add one or more sub-levels to the TOC. Is there a simple way to do that?

**Comment by marisademeglio** [comment]
Thanks! There's nothing at the moment to generate a complex TOC, though I don't think this would be a difficult addition. You do have the option of supplying your own, as described here 
https://github.com/marisademeglio/eleventypub?tab=readme-ov-file#what-are-the-toc-options.

**Comment by gautierchomel** [comment]
Wonderful, thanks (with my apologies for not reading the entire doc before opening an issue)

**Comment by marisademeglio** [comment]
Oh no problem, it's nice to hear someone is using it! Also it reminds me that I am overdue to upgrade the dependencies.
